### ISSUE TITLE
Broken Github Action

### ISSUE THREAD

**Issue by 0xsirsaif** [0xsirsaif/fastapiusers-edgedb#5]
- [x] set up Edgedb gh actions

```yml
    - uses: edgedb/setup-edgedb@v1
    - name: Setup Edgedb
      run: edgedb query "SELECT 'Hello from GitHub Actions'"
```
